name = "DismalWorldServer"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ddc519dae0bf26ba74726b51532689dfa0c1dde48450c3bb68698cfa6aff1f4"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
