name = "DismalWorldServer"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6732dad50bb359f0f5eb799fab6c8726293547c83a2ba1ebfff800e0842cde21"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
