name = "DismalWorldServer"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aa27a9b9b6738946dc225df3dde466d4dadb95825390ccc6bfefc23585bd19d"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
