name = "DismalWorldServer"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71353dc1106be4489252e7674da15ca7ee537c9b914a8370a7a57e92b3290cfc"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
