name = "DismalWorldServer"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7a25507931b0b2f3da91edb0fcbbc39a314cc4bdb86fa53db9ef88144f84e34"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
