
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				skeleton = true
				zombie = true
				spider = true
				creeper = true
				player = true

			[light_sources.settings.entities.tfc]
				bluegill = true
				crayfish = true
				largemouth_bass = true
				salmon = true
				goat = true
				lake_trout = true
				crappie = true
				rainbow_trout = true
				frog = true
				turkey = true
				smallmouth_bass = true
				grouse = true

